name: Testes

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  test:
    name: Verificar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Conferir repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Evita clones rasos

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
     # - name: Install tox and any other packages
     #   run: pip install tox
     # - name: Run tox
     #   run: tox -- --cov=archives_app --cov-report=xml --junitxml=junittest.xml

      - name: Criar arquivo .env
        run: |
          touch .env
          echo SECRET_KEY=secret_key >> .env
          echo DEBUG=True >> .env
          echo POSTGRES_HOST=db_archives >> .env
          echo POSTGRES_DB=postgres >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          cat .env

      - name: Executar pytest  
        run: sudo docker-compose run web_archives pytest --cov --cov-report xml:./coverage.xml

      - name: fix code coverage paths
        if: always()
        run: |
          sed -i 's/\/home\/runner\/work\/2021.2-SysArq-Archives\/2021.2-SysArq-Archives\//\/github\/workspace\//g' coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: 2021.2-SysArq-Archives
          verbose: true
